# Auto-generated by repackage_ctrlsys_core_ip.tcl.
proc init_gui {IPINST} {
    ipgui::add_param $IPINST -name Component_Name
    set page [ipgui::add_page $IPINST -name {Configuration}]
    ipgui::add_param $IPINST -name NUM_SENSORS -parent $page
    ipgui::add_param $IPINST -name BUFFER_SIZE -parent $page
}

proc update_PARAM_VALUE.NUM_SENSORS {PARAM_VALUE.NUM_SENSORS} {}
proc update_PARAM_VALUE.BUFFER_SIZE {PARAM_VALUE.BUFFER_SIZE} {}

proc validate_PARAM_VALUE.NUM_SENSORS {PARAM_VALUE.NUM_SENSORS} {
    return true
}

proc validate_PARAM_VALUE.BUFFER_SIZE {PARAM_VALUE.BUFFER_SIZE} {
    return true
}

proc update_MODELPARAM_VALUE.NUM_SENSORS {MODELPARAM_VALUE.NUM_SENSORS PARAM_VALUE.NUM_SENSORS} {
    set_property value [get_property value ${PARAM_VALUE.NUM_SENSORS}] ${MODELPARAM_VALUE.NUM_SENSORS}
}

proc update_MODELPARAM_VALUE.BUFFER_SIZE {MODELPARAM_VALUE.BUFFER_SIZE PARAM_VALUE.BUFFER_SIZE} {
    set_property value [get_property value ${PARAM_VALUE.BUFFER_SIZE}] ${MODELPARAM_VALUE.BUFFER_SIZE}
}
