# Auto-generated constraints for ctrlsys_core
# Generated by: C:/Users/gordo/Documents/CtrlSysV3/source/scripts/generate_constraints.tcl
# Config: C:/Users/gordo/Documents/CtrlSysV3/source/config/system_config.json
# TOP_MODULE_NAME: design_1
# NUM_SENSORS: 2
# NUM_SENSORS source: Block Design cell /ctrlsys_core_0
# SDA port base: sda_0
# SCL port base: scl_0

# Keep these constraints at the project level because package pins are board-specific.
# Mapping: sensor i -> SDA on DIOi_N, SCL on DIOi_P.

# Sensor pin constraints

# Sensor 0: DIO0_N/DIO0_P
set_property PACKAGE_PIN G18 [get_ports {sda_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sda_0[0]}]
set_property PULLUP true [get_ports {sda_0[0]}]
set_property SLEW SLOW [get_ports {sda_0[0]}]
set_property DRIVE 4 [get_ports {sda_0[0]}]
set_property PACKAGE_PIN G17 [get_ports {scl_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scl_0[0]}]
set_property PULLUP true [get_ports {scl_0[0]}]
set_property SLEW SLOW [get_ports {scl_0[0]}]
set_property DRIVE 4 [get_ports {scl_0[0]}]

# Sensor 1: DIO1_N/DIO1_P
set_property PACKAGE_PIN H17 [get_ports {sda_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sda_0[1]}]
set_property PULLUP true [get_ports {sda_0[1]}]
set_property SLEW SLOW [get_ports {sda_0[1]}]
set_property DRIVE 4 [get_ports {sda_0[1]}]
set_property PACKAGE_PIN H16 [get_ports {scl_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scl_0[1]}]
set_property PULLUP true [get_ports {scl_0[1]}]
set_property SLEW SLOW [get_ports {scl_0[1]}]
set_property DRIVE 4 [get_ports {scl_0[1]}]
