`timescale 1ns / 1ps

module ctrlsys_core_ip_wrapper (
    input wire clk,
    input wire rst_n,

    output wire       spi_sclk,
    output wire       spi_mosi,
    output wire       spi_cs_n,
    input  wire [3:0] spi_miso,

    output wire       intan_sclk,
    output wire       intan_mosi,
    output wire       intan_cs_n,
    input  wire [7:0] intan_miso,

    output wire axi_spi_io0_i,
    input  wire axi_spi_io0_o,
    input  wire axi_spi_io0_t,
    output wire axi_spi_io1_i,
    input  wire axi_spi_io1_o,
    input  wire axi_spi_io1_t,
    output wire axi_spi_sck_i,
    input  wire axi_spi_sck_o,
    input  wire axi_spi_sck_t,
    output wire axi_spi_ss_i,
    input  wire axi_spi_ss_o,
    input  wire axi_spi_ss_t,

    output wire          m_axis_tvalid,
    input  wire          m_axis_tready,
    output wire [63:0] m_axis_tdata,
    output wire [ 7:0] m_axis_tkeep,
    output wire          m_axis_tlast,

    input  wire        s00_axi_aclk,
    input  wire        s00_axi_aresetn,
    input  wire [ 5:0] s00_axi_awaddr,
    input  wire [ 2:0] s00_axi_awprot,
    input  wire        s00_axi_awvalid,
    output wire        s00_axi_awready,
    input  wire [31:0] s00_axi_wdata,
    input  wire [ 3:0] s00_axi_wstrb,
    input  wire        s00_axi_wvalid,
    output wire        s00_axi_wready,
    output wire [ 1:0] s00_axi_bresp,
    output wire        s00_axi_bvalid,
    input  wire        s00_axi_bready,
    input  wire [ 5:0] s00_axi_araddr,
    input  wire [ 2:0] s00_axi_arprot,
    input  wire        s00_axi_arvalid,
    output wire        s00_axi_arready,
    output wire [31:0] s00_axi_rdata,
    output wire [ 1:0] s00_axi_rresp,
    output wire        s00_axi_rvalid,
    input  wire        s00_axi_rready
);

    ctrlsys_core u_ctrlsys_core (
        .clk  (clk),
        .rst_n(rst_n),

        .spi_sclk(spi_sclk),
        .spi_mosi(spi_mosi),
        .spi_cs_n(spi_cs_n),
        .spi_miso(spi_miso),

        .intan_sclk(intan_sclk),
        .intan_mosi(intan_mosi),
        .intan_cs_n(intan_cs_n),
        .intan_miso(intan_miso),

        .axi_spi_io0_i(axi_spi_io0_i),
        .axi_spi_io0_o(axi_spi_io0_o),
        .axi_spi_io0_t(axi_spi_io0_t),
        .axi_spi_io1_i(axi_spi_io1_i),
        .axi_spi_io1_o(axi_spi_io1_o),
        .axi_spi_io1_t(axi_spi_io1_t),
        .axi_spi_sck_i(axi_spi_sck_i),
        .axi_spi_sck_o(axi_spi_sck_o),
        .axi_spi_sck_t(axi_spi_sck_t),
        .axi_spi_ss_i (axi_spi_ss_i),
        .axi_spi_ss_o (axi_spi_ss_o),
        .axi_spi_ss_t (axi_spi_ss_t),

        .m_axis_tvalid(m_axis_tvalid),
        .m_axis_tready(m_axis_tready),
        .m_axis_tdata (m_axis_tdata),
        .m_axis_tkeep (m_axis_tkeep),
        .m_axis_tlast (m_axis_tlast),

        .s00_axi_aclk   (s00_axi_aclk),
        .s00_axi_aresetn(s00_axi_aresetn),
        .s00_axi_awaddr (s00_axi_awaddr),
        .s00_axi_awprot (s00_axi_awprot),
        .s00_axi_awvalid(s00_axi_awvalid),
        .s00_axi_awready(s00_axi_awready),
        .s00_axi_wdata  (s00_axi_wdata),
        .s00_axi_wstrb  (s00_axi_wstrb),
        .s00_axi_wvalid (s00_axi_wvalid),
        .s00_axi_wready (s00_axi_wready),
        .s00_axi_bresp  (s00_axi_bresp),
        .s00_axi_bvalid (s00_axi_bvalid),
        .s00_axi_bready (s00_axi_bready),
        .s00_axi_araddr (s00_axi_araddr),
        .s00_axi_arprot (s00_axi_arprot),
        .s00_axi_arvalid(s00_axi_arvalid),
        .s00_axi_arready(s00_axi_arready),
        .s00_axi_rdata  (s00_axi_rdata),
        .s00_axi_rresp  (s00_axi_rresp),
        .s00_axi_rvalid (s00_axi_rvalid),
        .s00_axi_rready (s00_axi_rready)
    );

endmodule
